app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/demodb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 30
